
os2adgang-pilot:
  domain: adgang.stgai.itkdev.dk # wishful thinking: adgang.demo.os2ai.dk

  realm:
    name: test-kommune
    displayName: Test Kommune (kopi 7)
    test: true
  systems:
    - name: os2ai
      displayName: OS2ai
      description: OS2ai Systemet
      rootUrl: https://demo.os2ai.dk/
      adminUrl: https://demo.os2ai.dk/
      baseUrl: https://demo.os2ai.dk/
      # TODO: should be generated instead of being set here - but we also need to inject in client systems.
      # We probably need a better approach than simple templating.
      # An operator creates secrets on demand perhaps?
      secret: eB2mmD1tYX2hrByAJXbl6q6Zj4dvfBvP
      secretGenerationTime: "1769173701"
      redirectUris:
        - https://demo.os2ai.dk/*
      postLogoutRedirectUris: https://demo.os2ai.dk/*
      webOrigins:
        - +
      claims:
        - key: groups
          mappings:
            - entityId: http://adgang.os2.eu/roles/usersystemrole/os2ai/builder/1
              value: Builder
        - key: roles
          type: exclusive
          mappings:
            - entityId: http://adgang.os2.eu/roles/usersystemrole/os2ai/admin/1
              value: admin
            - entityId: http://adgang.os2.eu/roles/usersystemrole/os2ai/user/1
              value: user

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tlsSecret: keycloak-tls-secret
  db:
    vendor: postgres
    host: cloudnative-pg-cluster-rw
    database: os2adgang
    usernameSecret:
      name: cloudnative-pg-cluster-admin
      key: username
    passwordSecret:
      name: cloudnative-pg-cluster-admin
      key: password
